version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "db:database"
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    hostname: azure-sql
    container_name: Azure-SQL
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pass@@@@
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
