version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network:
      - backend
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    hostname: azure-sql
    container_name: Azure-SQL
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: pass
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    network:
      - backend
networks:
  backend:
    driver: bridge
